<?php

namespace Database\Seeders;

use App\Models\MarketplaceService;
use Illuminate\Database\Seeder;

class MarketplaceServicesSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            // LAUNCH PACKAGES (one-time, per marketplace)
            [
                'service_group' => 'launch',
                'marketplace' => 'all',
                'code' => 'LAUNCH_LITE',
                'name_ru' => 'Старт Lite',
                'name_uz' => 'Start Lite',
                'description_ru' => 'Запуск аккаунта с базовой настройкой',
                'description_uz' => 'Oddiy sozlash bilan akkaunt ishga tushirish',
                'unit_ru' => 'разово',
                'unit_uz' => 'bir marta',
                'price' => 1900000,
                'sku_limit' => 10,
                'sort' => 10,
            ],
            [
                'service_group' => 'launch',
                'marketplace' => 'all',
                'code' => 'LAUNCH_PRO',
                'name_ru' => 'Старт Pro',
                'name_uz' => 'Start Pro',
                'description_ru' => 'Профессиональный запуск с расширенной настройкой',
                'description_uz' => 'Kengaytirilgan sozlash bilan professional ishga tushirish',
                'unit_ru' => 'разово',
                'unit_uz' => 'bir marta',
                'price' => 3900000,
                'sku_limit' => 30,
                'sort' => 20,
            ],
            [
                'service_group' => 'launch',
                'marketplace' => 'all',
                'code' => 'LAUNCH_MAX',
                'name_ru' => 'Старт Max',
                'name_uz' => 'Start Max',
                'description_ru' => 'Максимальный пакет для крупного каталога',
                'description_uz' => 'Katta katalog uchun maksimal paket',
                'unit_ru' => 'разово',
                'unit_uz' => 'bir marta',
                'price' => 6900000,
                'sku_limit' => 60,
                'sort' => 30,
            ],
            [
                'service_group' => 'launch',
                'marketplace' => 'all',
                'code' => 'LAUNCH_OVER_SKU',
                'name_ru' => 'Дополнительный SKU при запуске',
                'name_uz' => 'Qo\'shimcha SKU ishga tushirishda',
                'description_ru' => 'Стоимость за каждый дополнительный товар сверх лимита пакета',
                'description_uz' => 'Paket limitidan ortiq har bir qo\'shimcha mahsulot narxi',
                'unit_ru' => 'за SKU',
                'unit_uz' => 'SKU uchun',
                'price' => 25000,
                'sku_limit' => null,
                'sort' => 40,
            ],

            // MANAGEMENT (monthly, per marketplace, 100 SKU included)
            [
                'service_group' => 'management',
                'marketplace' => 'all',
                'code' => 'MGMT_CONTROL',
                'name_ru' => 'Control',
                'name_uz' => 'Control',
                'description_ru' => 'Базовое управление маркетплейсом',
                'description_uz' => 'Marketpleys asosiy boshqaruvi',
                'unit_ru' => 'в месяц за 1 маркетплейс',
                'unit_uz' => 'oyiga 1 marketpleys uchun',
                'price' => 1790000,
                'sku_limit' => 100,
                'sort' => 10,
            ],
            [
                'service_group' => 'management',
                'marketplace' => 'all',
                'code' => 'MGMT_GROWTH',
                'name_ru' => 'Growth',
                'name_uz' => 'Growth',
                'description_ru' => 'Расширенное управление для растущего бизнеса',
                'description_uz' => 'O\'sib borayotgan biznes uchun kengaytirilgan boshqaruv',
                'unit_ru' => 'в месяц за 1 маркетплейс',
                'unit_uz' => 'oyiga 1 marketpleys uchun',
                'price' => 2190000,
                'sku_limit' => 100,
                'sort' => 20,
            ],
            [
                'service_group' => 'management',
                'marketplace' => 'all',
                'code' => 'MGMT_SCALE',
                'name_ru' => 'Scale',
                'name_uz' => 'Scale',
                'description_ru' => 'Премиум управление для масштабирования',
                'description_uz' => 'Kengaytirish uchun premium boshqaruv',
                'unit_ru' => 'в месяц за 1 маркетплейс',
                'unit_uz' => 'oyiga 1 marketpleys uchun',
                'price' => 3490000,
                'sku_limit' => 100,
                'sort' => 30,
            ],
            
            // MANAGEMENT - UZUM (cheaper)
            [
                'service_group' => 'management',
                'marketplace' => 'uzum',
                'code' => 'MGMT_CONTROL_UZUM',
                'name_ru' => 'Control',
                'name_uz' => 'Control',
                'description_ru' => 'Базовое управление',
                'description_uz' => 'Asosiy boshqaruv',
                'unit_ru' => 'в месяц за Uzum',
                'unit_uz' => 'Uzum uchun oyiga',
                'price' => 1490000,
                'sku_limit' => 100,
                'sort' => 11,
            ],
            [
                'service_group' => 'management',
                'marketplace' => 'uzum',
                'code' => 'MGMT_GROWTH_UZUM',
                'name_ru' => 'Growth',
                'name_uz' => 'Growth',
                'description_ru' => 'Расширенное управление',
                'description_uz' => 'Kengaytirilgan boshqaruv',
                'unit_ru' => 'в месяц за Uzum',
                'unit_uz' => 'Uzum uchun oyiga',
                'price' => 1890000,
                'sku_limit' => 100,
                'sort' => 21,
            ],
            [
                'service_group' => 'management',
                'marketplace' => 'uzum',
                'code' => 'MGMT_SCALE_UZUM',
                'name_ru' => 'Scale',
                'name_uz' => 'Scale',
                'description_ru' => 'Премиум управление',
                'description_uz' => 'Premium boshqaruv',
                'unit_ru' => 'в месяц за Uzum',
                'unit_uz' => 'Uzum uchun oyiga',
                'price' => 2690000,
                'sku_limit' => 100,
                'sort' => 31,
            ],
            
            // MANAGEMENT - COMPLEX (WB/Ozon/Yandex - more expensive)
            [
                'service_group' => 'management',
                'marketplace' => 'all', // For WB/Ozon/Yandex
                'code' => 'MGMT_CONTROL_COMPLEX',
                'name_ru' => 'Control',
                'name_uz' => 'Control',
                'description_ru' => 'Базовое управление',
                'description_uz' => 'Asosiy boshqaruv',
                'unit_ru' => 'в месяц за площадку',
                'unit_uz' => 'marketplace uchun oyiga',
                'price' => 1990000,
                'sku_limit' => 100,
                'sort' => 12,
            ],
            [
                'service_group' => 'management',
                'marketplace' => 'all',
                'code' => 'MGMT_GROWTH_COMPLEX',
                'name_ru' => 'Growth',
                'name_uz' => 'Growth',
                'description_ru' => 'Расширенное управление',
                'description_uz' => 'Kengaytirilgan boshqaruv',
                'unit_ru' => 'в месяц за площадку',
                'unit_uz' => 'marketplace uchun oyiga',
                'price' => 2390000,
                'sku_limit' => 100,
                'sort' => 22,
            ],
            [
                'service_group' => 'management',
                'marketplace' => 'all',
                'code' => 'MGMT_SCALE_COMPLEX',
                'name_ru' => 'Scale',
                'name_uz' => 'Scale',
                'description_ru' => 'Премиум управление',
                'description_uz' => 'Premium boshqaruv',
                'unit_ru' => 'в месяц за площадку',
                'unit_uz' => 'marketplace uchun oyiga',
                'price' => 3690000,
                'sku_limit' => 100,
                'sort' => 32,
            ],
            [
                'service_group' => 'management',
                'marketplace' => 'all',
                'code' => 'MGMT_OVER_10_SKU',
                'name_ru' => 'Дополнительно 10 SKU',
                'name_uz' => 'Qo\'shimcha 10 SKU',
                'description_ru' => 'Стоимость за каждые 10 товаров сверх 100 включенных',
                'description_uz' => '100 ta mahsulotdan ortiq har 10 ta uchun narx',
                'unit_ru' => 'за 10 SKU в месяц',
                'unit_uz' => '10 SKU uchun oyiga',
                'price' => 50000,
                'sku_limit' => null,
                'sort' => 40,
            ],

            // ADS ADD-ON (monthly, per marketplace)
            [
                'service_group' => 'ads_addon',
                'marketplace' => 'all',
                'code' => 'ADS_ADDON',
                'name_ru' => 'Управление рекламой',
                'name_uz' => 'Reklama boshqaruvi',
                'description_ru' => 'Настройка и ведение рекламных кампаний (бюджет не включен)',
                'description_uz' => 'Reklama kampaniyalarini sozlash va yuritish (byudjet kiritilmagan)',
                'unit_ru' => 'в месяц за 1 маркетплейс',
                'unit_uz' => 'oyiga 1 marketpleys uchun',
                'price' => 690000,
                'sku_limit' => null,
                'sort' => 10,
            ],

            // INFOGRAPHICS
            [
                'service_group' => 'infographics',
                'marketplace' => null,
                'code' => 'INFO_FIRST',
                'name_ru' => 'Инфографика основная',
                'name_uz' => 'Asosiy infografika',
                'description_ru' => 'Создание первой инфографики товара (только предмет, без модели)',
                'description_uz' => 'Mahsulot birinchi infografikasini yaratish (faqat buyum, modelsiz)',
                'unit_ru' => 'за товар',
                'unit_uz' => 'mahsulot uchun',
                'price' => 60000,
                'sku_limit' => null,
                'sort' => 10,
            ],
            [
                'service_group' => 'infographics',
                'marketplace' => null,
                'code' => 'INFO_COPY',
                'name_ru' => 'Копия/вариант',
                'name_uz' => 'Nusxa/variant',
                'description_ru' => 'Копия инфографики для вариантов одного товара',
                'description_uz' => 'Bitta mahsulot variantlari uchun infografika nusxasi',
                'unit_ru' => 'за копию',
                'unit_uz' => 'nusxa uchun',
                'price' => 40000,
                'sku_limit' => null,
                'sort' => 20,
            ],
        ];

        foreach ($services as $service) {
            MarketplaceService::updateOrCreate(
                ['code' => $service['code']],
                $service
            );
        }

        $this->command->info('Marketplace services seeded successfully, including Uzum and Complex pricing');
    }
}
