<?php

namespace Database\Seeders;

use App\Models\ServiceAddon;
use Illuminate\Database\Seeder;

class ServiceAddonsSeeder extends Seeder
{
    /**
     * Seed all service add-ons.
     * Pricing types: fixed|by_category|percent|manual
     */
    public function run(): void
    {
        $addons = [
            // ================== INBOUND (Приёмка) ==================
            [
                'code' => 'INB_PHOTO',
                'scope' => 'inbound',
                'title_ru' => 'Фотофиксация при приёмке',
                'title_uz' => 'Qabulda foto-fiksatsiya',
                'unit_ru' => 'за фото',
                'unit_uz' => 'har bir foto uchun',
                'pricing_type' => 'fixed',
                'value' => 500,
                'description_ru' => 'Фото товара/коробов при приёмке по запросу клиента',
                'description_uz' => 'Mijoz so\'roviga ko\'ra qabul paytida foto',
                'sort' => 10,
            ],
            [
                'code' => 'INB_COUNT_ITEM',
                'scope' => 'inbound',
                'title_ru' => 'Поштучный пересчёт',
                'title_uz' => 'Donabay sanash',
                'unit_ru' => 'за единицу',
                'unit_uz' => 'har bir dona uchun',
                'pricing_type' => 'fixed',
                'value' => 200,
                'description_ru' => 'Пересчёт товаров поштучно',
                'description_uz' => 'Tovarlarni donabay hisoblash',
                'sort' => 20,
            ],
            [
                'code' => 'INB_SORT_SKU',
                'scope' => 'inbound',
                'title_ru' => 'Сортировка по SKU',
                'title_uz' => 'SKU bo\'yicha saralash',
                'unit_ru' => 'за короб',
                'unit_uz' => 'har bir quti uchun',
                'pricing_type' => 'fixed',
                'value' => 7000,
                'description_ru' => 'Сортировка и распределение товаров по SKU',
                'description_uz' => 'Tovarlarni SKU bo\'yicha saralash va taqsimlash',
                'sort' => 30,
            ],
            [
                'code' => 'INB_REPACK',
                'scope' => 'inbound',
                'title_ru' => 'Переупаковка при приёмке',
                'title_uz' => 'Qabulda qayta qadoqlash',
                'unit_ru' => 'за короб',
                'unit_uz' => 'har bir quti uchun',
                'pricing_type' => 'fixed',
                'value' => 9000,
                'description_ru' => 'Переупаковка повреждённых коробов',
                'description_uz' => 'Buzilgan qutularni qayta qadoqlash',
                'sort' => 40,
            ],
            [
                'code' => 'INB_URGENT',
                'scope' => 'inbound',
                'title_ru' => 'Срочная приёмка (+20%)',
                'title_uz' => 'Tezkor qabul (+20%)',
                'unit_ru' => '% от стоимости приёмки',
                'unit_uz' => 'qabul narxidan %',
                'pricing_type' => 'percent',
                'value' => 0.20,
                'description_ru' => 'Наценка к приёмке при обработке «срочно»',
                'description_uz' => 'Tezkor ishlov uchun qabulga ustama',
                'sort' => 50,
            ],
            [
                'code' => 'INB_LABELING',
                'scope' => 'inbound',
                'title_ru' => 'Маркировка товаров',
                'title_uz' => 'Tovarlarni belgilash',
                'unit_ru' => 'за единицу',
                'unit_uz' => 'har bir dona uchun',
                'pricing_type' => 'fixed',
                'value' => 300,
                'description_ru' => 'Наклейка штрих-кодов и этикеток',
                'description_uz' => 'Shtrix-kod va etiketka yopish',
                'sort' => 60,
            ],

            // ================== PICKPACK (Сборка) ==================
            [
                'code' => 'PKP_BUBBLE',
                'scope' => 'pickpack',
                'title_ru' => 'Доп. защита (пупырка)',
                'title_uz' => 'Qo\'shimcha himoya (pufak plyonka)',
                'unit_ru' => 'за единицу',
                'unit_uz' => 'har bir dona uchun',
                'pricing_type' => 'fixed',
                'value' => 1500,
                'description_ru' => 'Дополнительная защитная упаковка пупырчатой плёнкой',
                'description_uz' => 'Pufakli plyonka bilan qo\'shimcha himoya qadoqlash',
                'sort' => 10,
            ],
            [
                'code' => 'PKP_STRETCH',
                'scope' => 'pickpack',
                'title_ru' => 'Стрейч-обмотка',
                'title_uz' => 'Streych o\'rash',
                'unit_ru' => 'за заказ',
                'unit_uz' => 'har bir buyurtma uchun',
                'pricing_type' => 'fixed',
                'value' => 3000,
                'description_ru' => 'Обмотка заказа стрейч-плёнкой',
                'description_uz' => 'Buyurtmani streych plyonka bilan o\'rash',
                'sort' => 20,
            ],
            [
                'code' => 'PKP_FRAGILE',
                'scope' => 'pickpack',
                'title_ru' => 'Обработка «Хрупкое»',
                'title_uz' => '«Mo\'rt» belgilash',
                'unit_ru' => 'за заказ',
                'unit_uz' => 'har bir buyurtma uchun',
                'pricing_type' => 'fixed',
                'value' => 2000,
                'description_ru' => 'Специальная маркировка и упаковка хрупких товаров',
                'description_uz' => 'Mo\'rt tovarlarni maxsus belgilash va qadoqlash',
                'sort' => 30,
            ],
            [
                'code' => 'PKP_GIFT',
                'scope' => 'pickpack',
                'title_ru' => 'Подарочная упаковка',
                'title_uz' => 'Sovg\'a qadoq',
                'unit_ru' => 'за единицу',
                'unit_uz' => 'har bir dona uchun',
                'pricing_type' => 'fixed',
                'value' => 8000,
                'description_ru' => 'Оформление товара в подарочную упаковку',
                'description_uz' => 'Tovarni sovg\'a qadoqiga joylashtirish',
                'sort' => 40,
            ],
            [
                'code' => 'PKP_PHOTO',
                'scope' => 'pickpack',
                'title_ru' => 'Фото готовой сборки',
                'title_uz' => 'Tayyor yig\'im fotosi',
                'unit_ru' => 'за заказ',
                'unit_uz' => 'har bir buyurtma uchun',
                'pricing_type' => 'fixed',
                'value' => 4000,
                'description_ru' => 'Фотография собранного заказа перед отправкой',
                'description_uz' => 'Jo\'natishdan oldin yig\'ilgan buyurtma surati',
                'sort' => 50,
            ],
            [
                'code' => 'PKP_INSERT',
                'scope' => 'pickpack',
                'title_ru' => 'Вложение материалов',
                'title_uz' => 'Materiallarni qo\'shish',
                'unit_ru' => 'за вложение',
                'unit_uz' => 'har bir qo\'shish uchun',
                'pricing_type' => 'fixed',
                'value' => 200,
                'description_ru' => 'Вложение рекламных материалов, визиток',
                'description_uz' => 'Reklama materiallari, tashrif qog\'ozlarini qo\'shish',
                'sort' => 60,
            ],
            [
                'code' => 'PKP_PROTECT_CAT',
                'scope' => 'pickpack',
                'title_ru' => 'Усиленная защита (по размеру)',
                'title_uz' => 'Kuchaytirilgan himoya (o\'lcham bo\'yicha)',
                'unit_ru' => 'за единицу',
                'unit_uz' => 'har bir dona uchun',
                'pricing_type' => 'by_category',
                'value' => null,
                'meta' => ['MICRO' => 200, 'MGT' => 300, 'SGT' => 500, 'KGT' => 800],
                'description_ru' => 'Дополнительная защитная упаковка с ценой по размеру',
                'description_uz' => 'Tovar o\'lchamiga qarab qo\'shimcha himoya qadoqlash',
                'sort' => 70,
            ],

            // ================== STORAGE (Хранение) ==================
            [
                'code' => 'STG_HANDLING',
                'scope' => 'storage',
                'title_ru' => 'Перемещение/перебор на складе',
                'title_uz' => 'Omborda qayta joylash',
                'unit_ru' => 'за короб',
                'unit_uz' => 'har bir quti uchun',
                'pricing_type' => 'fixed',
                'value' => 5000,
                'description_ru' => 'Ручное перемещение или перебор товаров',
                'description_uz' => 'Tovarlarni qo\'lda ko\'chirish yoki qayta saralash',
                'sort' => 10,
            ],
            [
                'code' => 'STG_PALLET',
                'scope' => 'storage',
                'title_ru' => 'Хранение на паллете',
                'title_uz' => 'Palletda saqlash',
                'unit_ru' => 'за паллето-день',
                'unit_uz' => 'har bir pallet-kun uchun',
                'pricing_type' => 'fixed',
                'value' => 15000,
                'description_ru' => 'Хранение крупногабаритных товаров на паллетах',
                'description_uz' => 'Katta o\'lchamli tovarlarni palletlarda saqlash',
                'sort' => 20,
            ],
            [
                'code' => 'STG_CLIMATE',
                'scope' => 'storage',
                'title_ru' => 'Климат-контроль',
                'title_uz' => 'Iqlim nazorati',
                'unit_ru' => 'за коробко-день',
                'unit_uz' => 'har bir quti-kun uchun',
                'pricing_type' => 'fixed',
                'value' => 500,
                'description_ru' => 'Хранение в зоне с контролем температуры',
                'description_uz' => 'Harorat nazorati zonasida saqlash',
                'sort' => 30,
            ],

            // ================== SHIPPING (Отправка) ==================
            [
                'code' => 'SHP_URGENT_12',
                'scope' => 'shipping',
                'title_ru' => 'Срочная отправка до 12:00 (+20%)',
                'title_uz' => '12:00 gacha tezkor (+20%)',
                'unit_ru' => '% от стоимости доставки',
                'unit_uz' => 'yetkazish narxidan %',
                'pricing_type' => 'percent',
                'value' => 0.20,
                'description_ru' => 'Наценка к доставке при срочности',
                'description_uz' => 'Tezkor jo\'natish uchun yetkazishga ustama',
                'sort' => 10,
            ],
            [
                'code' => 'SHP_EXTRA_DROP',
                'scope' => 'shipping',
                'title_ru' => 'Дополнительная точка сдачи',
                'title_uz' => 'Qo\'shimcha topshirish nuqtasi',
                'unit_ru' => 'за точку',
                'unit_uz' => 'har bir nuqta uchun',
                'pricing_type' => 'fixed',
                'value' => 10000,
                'description_ru' => 'Сдача отправления в дополнительный ПВЗ',
                'description_uz' => 'Jo\'natmani qo\'shimcha PVZga topshirish',
                'sort' => 20,
            ],
            [
                'code' => 'SHP_INSURANCE',
                'scope' => 'shipping',
                'title_ru' => 'Страхование отправления (2%)',
                'title_uz' => 'Jo\'natmani sug\'urtalash (2%)',
                'unit_ru' => '% от стоимости',
                'unit_uz' => 'qiymatdan %',
                'pricing_type' => 'percent',
                'value' => 0.02,
                'description_ru' => 'Страхование груза на полную стоимость',
                'description_uz' => 'Yukni to\'liq qiymatga sug\'urtalash',
                'sort' => 30,
            ],
            [
                'code' => 'SHP_COD',
                'scope' => 'shipping',
                'title_ru' => 'Наложенный платёж (3%)',
                'title_uz' => 'Yetkazib berishda to\'lov (3%)',
                'unit_ru' => '% от суммы',
                'unit_uz' => 'summadan %',
                'pricing_type' => 'percent',
                'value' => 0.03,
                'description_ru' => 'Услуга приёма оплаты при доставке',
                'description_uz' => 'Yetkazib berishda to\'lovni qabul qilish xizmati',
                'sort' => 40,
            ],
            [
                'code' => 'SHP_EXPRESS',
                'scope' => 'shipping',
                'title_ru' => 'Экспресс-доставка (24ч)',
                'title_uz' => 'Ekspress yetkazish (24s)',
                'unit_ru' => 'за отправку',
                'unit_uz' => 'har bir jo\'natma uchun',
                'pricing_type' => 'by_category',
                'value' => null,
                'meta' => ['MICRO' => 5000, 'MGT' => 8000, 'SGT' => 15000, 'KGT' => 25000],
                'description_ru' => 'Доставка в течение 24 часов',
                'description_uz' => '24 soat ichida yetkazib berish',
                'sort' => 50,
            ],

            // ================== RETURNS (Возвраты) ==================
            [
                'code' => 'RET_LOGISTICS',
                'scope' => 'returns',
                'title_ru' => 'Обратная логистика',
                'title_uz' => 'Qaytish logistikasi',
                'unit_ru' => 'как доставка',
                'unit_uz' => 'yetkazish kabi',
                'pricing_type' => 'by_category',
                'value' => null,
                'meta' => ['mode' => 'delivery_like', 'MICRO' => 2000, 'MGT' => 4000, 'SGT' => 8000, 'KGT' => 20000],
                'description_ru' => 'Обратная доставка возврата на склад',
                'description_uz' => 'Qaytgan tovarni omborga yetkazish',
                'sort' => 10,
            ],
            [
                'code' => 'RET_CHECK',
                'scope' => 'returns',
                'title_ru' => 'Проверка возврата',
                'title_uz' => 'Qaytgan tovarni tekshirish',
                'unit_ru' => 'за единицу',
                'unit_uz' => 'har bir dona uchun',
                'pricing_type' => 'by_category',
                'value' => null,
                'meta' => ['MICRO' => 300, 'MGT' => 500, 'SGT' => 800, 'KGT' => 1200],
                'description_ru' => 'Проверка состояния возвращённого товара',
                'description_uz' => 'Qaytarilgan tovar holatini tekshirish',
                'sort' => 20,
            ],
            [
                'code' => 'RET_RESTOCK',
                'scope' => 'returns',
                'title_ru' => 'Подготовка к повторной продаже',
                'title_uz' => 'Qayta sotuvga tayyorlash',
                'unit_ru' => 'за единицу',
                'unit_uz' => 'har bir dona uchun',
                'pricing_type' => 'by_category',
                'value' => null,
                'meta' => ['MICRO' => 200, 'MGT' => 400, 'SGT' => 700, 'KGT' => 1000],
                'description_ru' => 'Переупаковка товара для повторной продажи',
                'description_uz' => 'Tovarni qayta sotish uchun qayta qadoqlash',
                'sort' => 30,
            ],

            // ================== OTHER (Другое) ==================
            [
                'code' => 'OTH_PHOTO_PRODUCT',
                'scope' => 'other',
                'title_ru' => 'Фотосъёмка товара',
                'title_uz' => 'Tovarni suratga olish',
                'unit_ru' => 'за товар',
                'unit_uz' => 'har bir tovar uchun',
                'pricing_type' => 'fixed',
                'value' => 5000,
                'description_ru' => 'Профессиональная фотосъёмка для каталога',
                'description_uz' => 'Katalog uchun professional suratga olish',
                'sort' => 10,
            ],
            [
                'code' => 'OTH_MANUAL_LINE',
                'scope' => 'other',
                'title_ru' => 'Ручная строка счёта',
                'title_uz' => 'Qo\'lda hisob qatori',
                'unit_ru' => 'по согласованию',
                'unit_uz' => 'kelishilgan narxda',
                'pricing_type' => 'manual',
                'value' => null,
                'meta' => ['mode' => 'manager_amount_input'],
                'description_ru' => 'Индивидуальные работы по запросу клиента',
                'description_uz' => 'Mijoz so\'roviga ko\'ra individual ishlar',
                'sort' => 100,
            ],
        ];

        foreach ($addons as $addonData) {
            ServiceAddon::updateOrCreate(
                ['code' => $addonData['code']],
                $addonData
            );
        }

        $this->command->info('Service addons seeded: ' . count($addons) . ' items');
    }
}
